version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: vtelegram-calendar-bot
    restart: unless-stopped
    volumes:
      - ./data:/data
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
    env_file:
      - .env